# Generated by Django 3.1.7 on 2021-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('experiences', models.CharField(max_length=255)),
                ('expectations', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
            ],
        ),
    ]
