# Generated by Django 3.1.7 on 2021-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='profile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
