# Generated by Django 3.1.7 on 2021-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_jobs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobdescription',
            field=models.CharField(max_length=255),
        ),
    ]
